ci:
- all:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

build_system:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - 'CMake*'
      - '**/CMakeLists.txt'
      - '**/*.cmake'

sigutils:
- all:
  - changed-files:
    - any-glob-to-any-file: 'src/**'
    - all-globs-to-all-files: '!src/CMakeLists.txt'

documentation:
- all:
  - changed-files:
    - any-glob-to-any-file: 'doc/**'
    - all-globs-to-all-files: '!doc/CMakeLists.txt'

tests:
- all:
  - changed-files:
    - any-glob-to-any-file: 'tests/**'
    - all-globs-to-all-files: '!tests/CMakeLists.txt'
