ci:
  - .github/workflows/**/*
  - .github/actions/**/*

build_system:
  - 'CMake*'
  - '**/CMakeLists.txt'
  - '**/*.cmake'

sigutils:
  - src/**/*
  - '!src/CMakeLists.txt'

documentation:
  - doc/**/*
  - '!doc/CMakeLists.txt'

tests:
  - tests/**/*
  - '!tests/CMakeLists.txt'
