/*

  Copyright (C) 2016 Gonzalo José Carracedo Carballal

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this program.  If not, see
  <http://www.gnu.org/licenses/>

*/

#include <stdio.h>
#include <math.h>
#include <string.h>
#include <time.h>
#include "test.h"

SUBOOL
su_sigbuf_pool_helper_dump_matlab(
    const void *data,
    size_t size,
    SUBOOL is_complex,
    const char *directory,
    const char *name)
{
  char *filename = NULL;
  SUBOOL result;

  filename = strbuild("%s/%s.m", directory, name);
  if (filename == NULL) {
    SU_ERROR("Memory error while building filename\n");
    goto fail;
  }

  if (is_complex)
    result = su_test_complex_buffer_dump_matlab(
        (const SUCOMPLEX *) data,
        size,
        filename,
        name);
  else
    result = su_test_buffer_dump_matlab(
        (const SUFLOAT *) data,
        size,
        filename,
        name);

  free(filename);

  return result;

fail:
  if (filename != NULL)
    free(filename);

  return SU_FALSE;
}

SUBOOL
su_sigbuf_pool_dump_matlab(const su_sigbuf_pool_t *pool)
{
  su_sigbuf_t *this;
  unsigned int i;
  char *filename = NULL;
  FILE *fp = NULL;
  time_t now;

  if ((filename = strbuild("%s.m", pool->name)) == NULL) {
     SU_ERROR("Failed to build main script file name\n");
     goto fail;
   }

   if ((fp = fopen(filename, "w")) == NULL) {
     SU_ERROR("Cannot create main script `%s': %s\n", filename, strerror(errno));
     goto fail;
   }

   free(filename);
   filename = NULL;

   time(&now);

   SU_SYSCALL_ASSERT(
       fprintf(
           fp,
           "%% Autogenerated MATLAB script for sigbuf pool `%s'\n",
           pool->name));
   SU_SYSCALL_ASSERT(
       fprintf(
           fp,
           "%% File generated on %s",
           ctime(&now)));

   FOR_EACH_PTR(this, i, pool->sigbuf) {
     if (!su_sigbuf_pool_helper_dump_matlab(
         this->buffer,
         this->size,
         this->is_complex,
         pool->name,
         this->name))
       goto fail;

     SU_SYSCALL_ASSERT(
         fprintf(
             fp,
             "%% %s: %s buffer, %d elements\n",
             this->name,
             this->is_complex ? "complex" : "float",
             this->size));
     SU_SYSCALL_ASSERT(
         fprintf(
             fp,
             "source('%s/%s.m');\n\n",
             pool->name,
             this->name));
   }

   fclose(fp);
   fp = NULL;

   return SU_TRUE;

 fail:
   if (filename != NULL)
     free(filename);

   if (fp != NULL)
     fclose(fp);

   return SU_FALSE;
}

