name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:

    - name: Install dependencies
      run: sudo apt-get install libsndfile1-dev libvolk2-dev libfftw3-dev

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Get short hash
      id: vars
      run: cd ${{github.workspace}}/sigutils/ && echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Make Debian package
      run: ./makedeb.sh 0.3.0 ${{steps.vars.outputs.sha_short}}

    - name: Upload deb artifact
      uses: actions/upload-artifact@v3
      with:
        name: libsigutils_0.3.0-${{steps.vars.outputs.sha_short}}_amd64.deb
        path: libsigutils_0.3.0-${{steps.vars.outputs.sha_short}}_amd64.deb

    - name: Upload dev deb artifact
      uses: actions/upload-artifact@v3
      with:
        name: libsigutils-dev_0.3.0-${{steps.vars.outputs.sha_short}}_amd64.deb
        path: libsigutils-dev_0.3.0-${{steps.vars.outputs.sha_short}}_amd64.deb

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: brew install libsndfile volk fftw

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-cc mingw-w64-x86_64-make mingw-w64-x86_64-cmake mingw-w64-x86_64-libsndfile mingw-w64-x86_64-fftw mingw-w64-x86_64-volk

    - name: Configure
      run: cmake -B '${{github.workspace}}/build' -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
      
    - name: Build
      run: cmake --build '${{github.workspace}}/build' --config ${{env.BUILD_TYPE}}

    - name: Upload dll file
      uses: actions/upload-artifact@v3
      with:
        name: libsigutils.dll
        path: ${{github.workspace}}/build/libsigutils.dll
